// TMDB official genre IDs used to build mood-based discover queries.
const GENRE = {
  action: 28,
  adventure: 12,
  animation: 16,
  comedy: 35,
  crime: 80,
  documentary: 99,
  drama: 18,
  family: 10751,
  fantasy: 14,
  history: 36,
  horror: 27,
  music: 10402,
  mystery: 9648,
  romance: 10749,
  scifi: 878,
  thriller: 53,
  war: 10752,
  western: 37,
}

export const MOODS = [
  {
    id: 'happy',
    label: 'Happy',
    emoji: '😊',
    color: '#FFC857',
    description: 'Feel-good films to lift your spirits',
    genres: [GENRE.comedy, GENRE.family, GENRE.animation],
    sortBy: 'popularity.desc',
    minRating: 6,
  },
  {
    id: 'sad',
    label: 'Sad',
    emoji: '😢',
    color: '#5B7DB1',
    description: 'Emotional dramas for a good cry',
    genres: [GENRE.drama],
    sortBy: 'vote_average.desc',
    minRating: 6.5,
  },
  {
    id: 'excited',
    label: 'Excited',
    emoji: '🤩',
    color: '#FF6B35',
    description: 'High-energy thrills and adventure',
    genres: [GENRE.action, GENRE.adventure, GENRE.thriller],
    sortBy: 'popularity.desc',
    minRating: 6,
  },
  {
    id: 'relaxed',
    label: 'Relaxed',
    emoji: '😌',
    color: '#6FCF97',
    description: 'Easy watching, low stress',
    genres: [GENRE.family, GENRE.animation, GENRE.music],
    sortBy: 'vote_average.desc',
    minRating: 6,
  },
  {
    id: 'romantic',
    label: 'Romantic',
    emoji: '💕',
    color: '#E0457B',
    description: 'Love stories and romance',
    genres: [GENRE.romance],
    sortBy: 'popularity.desc',
    minRating: 6,
  },
  {
    id: 'motivated',
    label: 'Motivated',
    emoji: '🔥',
    color: '#E50914',
    description: 'Inspiring stories to fuel ambition',
    genres: [GENRE.drama, GENRE.history],
    sortBy: 'vote_average.desc',
    minRating: 7,
  },
  {
    id: 'action',
    label: 'Action',
    emoji: '💥',
    color: '#D7263D',
    description: 'Explosive action and adrenaline',
    genres: [GENRE.action],
    sortBy: 'popularity.desc',
    minRating: 5.5,
  },
  {
    id: 'horror',
    label: 'Horror',
    emoji: '👻',
    color: '#8E44AD',
    description: 'Scares and suspense',
    genres: [GENRE.horror],
    sortBy: 'popularity.desc',
    minRating: 5.5,
  },
  {
    id: 'comedy',
    label: 'Comedy',
    emoji: '😂',
    color: '#F2C94C',
    description: 'Laugh-out-loud entertainment',
    genres: [GENRE.comedy],
    sortBy: 'popularity.desc',
    minRating: 5.5,
  },
  {
    id: 'scifi',
    label: 'Sci-Fi',
    emoji: '🚀',
    color: '#2EC4B6',
    description: 'Futuristic worlds and ideas',
    genres: [GENRE.scifi],
    sortBy: 'popularity.desc',
    minRating: 6,
  },
]

export const getMoodById = (id) => MOODS.find((m) => m.id === id)
